<?php


namespace iflow\template\document\Tag;


use iflow\template\config\Config;
use iflow\template\document\abstracts\tagAbstract;
use iflow\template\document\Parser\DOMNodeParser;
use iflow\template\document\Parser\ParserHtml;

class echoTag extends tagAbstract
{
    public string $tagName = "echo";
    protected array $hiddenAttributes = ["tag"];

    public function parser(DOMNodeParser $node, Config $config, ParserHtml $parserHtml): static
    {
        parent::parser($node, $config, $parserHtml); // TODO: Change the autogenerated stub
        $this->html = "<?={$this->node -> nodeValue}?>";
        return $this;
    }
}