<?php

namespace iflow\template\document\Tag;

use iflow\template\config\Config;
use iflow\template\document\abstracts\TagAbstract;
use iflow\template\document\Parser\DOMNodeParser;
use iflow\template\document\Parser\ParserHtml;

class literalTag extends TagAbstract {

    public string $tagName = '';
    protected string $defaultTagName = '';

    public function parser(DOMNodeParser $node, Config $config, ParserHtml $parserHtml): static {
        parent::parser($node, $config, $parserHtml); // TODO: Change the autogenerated stub
        $this->html = $node -> toString();
        return $this;
    }

}