<?php


namespace iflow\template\document\Tag;


use iflow\template\Config\Config;
use iflow\template\document\abstracts\TagAbstract;
use iflow\template\document\Parser\DOMNodeParser;
use iflow\template\document\Parser\ParserHtml;

class PHPScript extends TagAbstract {

    public string $tagName = "phpScript";

    protected array $hiddenAttributes = [ 'tag' ];

    public function parser(DOMNodeParser $node, Config $config, ParserHtml $parserHtml): static
    {
        parent::parser($node, $config, $parserHtml); // TODO: Change the autogenerated stub
        $this->html = sprintf("<?php %s ?>", $this->node -> nodeValue);
        return $this;
    }
}